################################# Default configuration ###################
# provide your domain here
baseURL = "/"
# theme
theme = "dot-hugo"
# site title
title = "Metapsy Documentation"
# disable language
disableLanguages = ["fr"]
# google analytics
# googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "Metapsy Documentation"
author = "Metapsy Collaboration"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#313f45"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "fira sans" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
# [[params.social]]
# icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
# name = "Facebook"
# link = "#"

# [[params.social]]
# icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
# name = "Twitter"
# link = "https://www.twitter.com/pcuijpers"
  
# [[params.social]]
# icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
# name = "Github"
# link = "https://github.com/metapsy-project"
  
# [[params.social]]
# icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
# name = "Linkedin"
# link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "&copy; <script>document.write(new Date().getFullYear())</script> Metapsy Collaboration"

# banner
[Languages.en.params.banner]
title = "The Metapsy Documentation"
subtitle = "Use this website to search the technical documentation of the project"
bg_image = "images/banner.jpg"
placeholder = "Search for topics..."

# call to action
[Languages.en.params.cta]
enable = false
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
[Languages.en.params.cta.button]
enable = false
label = "contact us"
link = "contact/"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = ""
weight = 1


# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "topics"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "General Information"
  url = "general/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "Databases"
  url = "databases/"
  weight = 2
  
   [[Languages.en.menu.main]]
  parent = "topics"
  name = "Data Preparation"
  url = "data-preparation/"
  weight = 3

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "Data Release"
  url = "release/"
  weight = 4

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "R Packages & API"
  url = "r-packages/"
  weight = 5

  [[Languages.en.menu.main]]
  parent = "topics"
  name = "Meta-Analysis Tool"
  url = "meta-analysis-tool/"
  weight = 6

custom_css = ["css/custom.css"]
custom_js = ["js/custom.js"]
